spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cocktail?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    com:
      tutorial:
        spring-boot: DEBUG
  path: logs

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true